# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is your recipe called?', max_length=128)),
                ('prep_time', models.FloatField(blank=True, choices=[(0.25, '15 minutes'), (0.5, '30 minutes'), (0.75, '45 minutes'), (1.0, '1 hour'), (1.25, '1 hour 15 minutes'), (1.5, '1 hour 30 minutes'), (1.75, '1 hour 45 minutes'), (2.0, '2 hours'), (2.25, '2 hours 15 minutes'), (2.5, '2 hours 30 minutes'), (2.75, '2 hours 45 minutes'), (3.0, '3 hours'), (3.25, '3 hours 15 minutes'), (3.5, '3 hours 30 minutes'), (3.75, '3 hours 45 minutes'), (4.0, '4+ hours')], null=True)),
                ('cook_time', models.FloatField(blank=True, choices=[(0.25, '15 minutes'), (0.5, '30 minutes'), (0.75, '45 minutes'), (1.0, '1 hour'), (1.25, '1 hour 15 minutes'), (1.5, '1 hour 30 minutes'), (1.75, '1 hour 45 minutes'), (2.0, '2 hours'), (2.25, '2 hours 15 minutes'), (2.5, '2 hours 30 minutes'), (2.75, '2 hours 45 minutes'), (3.0, '3 hours'), (3.25, '3 hours 15 minutes'), (3.5, '3 hours 30 minutes'), (3.75, '3 hours 45 minutes'), (4.0, '4+ hours')], null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
