# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='privacy',
            field=models.CharField(choices=[('pu', 'Public'), ('pr', 'Private'), ('fr', 'Friends Only')], default='pu', max_length=2),
        ),
    ]
