# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Salsa Ranchera', help_text='What is your recipe called?', max_length=128),
            preserve_default=False,
        ),
    ]
