# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20160501_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.FloatField(blank=True, choices=[(0.25, '15 minutes'), (0.5, '30 minutes'), (0.75, '45 minutes'), (1, '1 hour'), (1.25, '1 hour 15 minutes'), (1.5, '1 hour 30 minutes'), (1.75, '1 hour 45 minutes'), (2, '2 hours'), (2.25, '2 hours 15 minutes'), (2.5, '2 hours 30 minutes'), (2.75, '2 hours 45 minutes'), (3, '3 hours'), (3.25, '3 hours 15 minutes'), (3.5, '3 hours 30 minutes'), (3.75, '3 hours 45 minutes'), (4, '4+ hours')], null=True),
        ),
    ]
