# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20160501_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 2, 23, 57, 9, 34111, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
