# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientrelationship',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipe', to='recipe.Recipe'),
        ),
    ]
