# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_profile', '0002_auto_20160502_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
    ]
